### PR TITLE
Process restructuring

### PR DESCRIPTION
**Pull request by johntruckenbrodt**
This is a major restructuring to solve several shortcomings:
- the processor now accepts geometries spanning multipe UTM zones (https://github.com/SAR-ARD/S1_NRB/issues/32)
- the SNAP processing has been outsourced to a new module `snap`
- SNAP processing is now much more efficient by
  + combining all procesing steps of `pyroSAR.snap.geocode` and `pyroSAR.snap.noise_power` (https://github.com/SAR-ARD/S1_NRB/issues/39)
  + reusing intermediate processing output for multi-UTM processing
  + geocoding only to areas that are needed for the current UTM zone
- no longer create DEM MGRS tiles but rather only create scene-specific mosaics in EPSG:4326 (the MGRS tiling was done to save time because EGM2008 conversion used to be very slow. This is no longer an issue nad the storage space can thus be saved)

### CODE REVIEW

**Comment by maawoo** [comment]
Great, thanks John! Is it still work in progress? I could do some tests later today.

**Comment by johntruckenbrodt** [comment]
Hi Marco. This is almost ready. However, so far I have only fully tested it with IW GRD images because for SLCs I got a weird SNAP error during terrain flattening, something about slant range - ground range lookup tables. Haven't figured out what the source is yet.  
You are very welcome to give it a try. I was going to ask you to revise the logging functionality. The pyroSAR log messages are now printed twice. I don't quite understand your logging module yet :sweat_smile:.

**Comment by maawoo** [comment]
The duplicate log messages are now fixed and I added a few other improvements. 

```Error: SARGeoCoding: srgrConvParams not set``` is the one you also get when processing SLC, right?
TF works with `tf.parameters['outputSimulatedImage'] = False`, but other than that I didn't find anything else 😕

**Comment by johntruckenbrodt** [comment]
Sorry @maawoo, I forgot to mention that this PR depends on changes in pyroSAR in https://github.com/johntruckenbrodt/pyroSAR/pull/225 and https://github.com/johntruckenbrodt/pyroSAR/tree/feature/dem_enhance. It seems you have figured that out yourself anyways though :muscle:.

**Comment by maawoo** [comment]
Yes, I figured that out 🙂 
The problem also occurs in the SNAP GUI and using an auto-downloaded DEM. So two factors that can be ruled out.

Screenshot 2022-09-19 at 10 49 14

-----------

I just had a look into the TF source code looking for `srgrConvParams` and I think [line 812](https://github.com/senbox-org/s1tbx/blob/a78d79745e1629dafaf922708e1e4cc8f64f5f14/s1tbx-op-sar-processing/src/main/java/org/esa/s1tbx/sar/gpf/geometric/TerrainFlatteningOp.java#L812) needs to be moved after the `if (isGRD)` clause [line 820](https://github.com/senbox-org/s1tbx/blob/a78d79745e1629dafaf922708e1e4cc8f64f5f14/s1tbx-op-sar-processing/src/main/java/org/esa/s1tbx/sar/gpf/geometric/TerrainFlatteningOp.java#L820). But maybe I'm wrong 😅 Anyway, I think this issue is out of our hands and needs to be reported.

**Comment by maawoo** [comment]
I just had a look into the TF source code looking for `srgrConvParams` and I think [line 812](https://github.com/senbox-org/s1tbx/blob/a78d79745e1629dafaf922708e1e4cc8f64f5f14/s1tbx-op-sar-processing/src/main/java/org/esa/s1tbx/sar/gpf/geometric/TerrainFlatteningOp.java#L812) needs to be moved after the `if (isGRD)` clause [line 820](https://github.com/senbox-org/s1tbx/blob/a78d79745e1629dafaf922708e1e4cc8f64f5f14/s1tbx-op-sar-processing/src/main/java/org/esa/s1tbx/sar/gpf/geometric/TerrainFlatteningOp.java#L820). But maybe I'm wrong 😅 Anyway, I think this issue is out of our hands and needs to be reported.

**Comment by johntruckenbrodt** [comment]
Thanks @maawoo for having a look. I have created an issue:
https://forum.step.esa.int/t/terrain-flattening-output-simulated-image-fails-for-s1-slcs/37359

**Pull request merged**
